// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import FeaturesBentoGridCta from "@/components/sections/features/FeaturesBentoGridCta";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
              <FeaturesBentoGridCta
        textAnimation="fade"
        tag="About Me"
        title="My Core Values"
        description="Committed to entrepreneurship, independence, and a strong Switzerland."
        features={[{"imageSrc":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80","title":"Entrepreneurship","description":"Leading EMS-CHEMIE with a focus on innovation and global success."},{"title":"Political Commitment","imageSrc":"https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&q=80","description":"Serving as National Councilor to advocate for a strong Swiss economy."},{"description":"Defending Swiss sovereignty and self-determination.","title":"Independence","imageSrc":"https://images.unsplash.com/photo-1527668752968-14dc70a27c95?w=600&q=80"},{"description":"Rooted in Swiss values and dedicated to future generations.","title":"Family & Tradition","imageSrc":"https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&q=80"}]}
        ctaButton={{"text":"Learn more","href":"https://www.martullo-blocher.ch/"}}
      />
            </div>
  );
}
