// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import FeaturesBentoGridCta from "@/components/sections/features/FeaturesBentoGridCta";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
              <FeaturesBentoGridCta
        textAnimation="fade"
        tag="Über mich"
        title="Magdalena Martullo-Blocher"
        description="Unternehmerin und Nationalrätin für eine starke Schweiz."
        features={[{"title":"Persönliches","imageSrc":"https://images.unsplash.com/photo-1527668752968-14dc70a27c95?w=600&q=80","description":"Wohnort: Meilen und Lenzerheide. Jahrgang: 1969. Zivilstand: verheiratet, 3 Kinder. Hobbies: Familie, Wandern, Berge."},{"description":"lic.oec. HSG, Unternehmerin EMS-CHEMIE AG. Vize-Präsidentin und Delegierte des Verwaltungsrates der EMS-CHEMIE HOLDING AG.","imageSrc":"https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1783293657977-32e64cu3.jpg","title":"Beruf"},{"imageSrc":"https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&q=80","description":"Nationalrätin SVP Graubünden, Verantwortliche für die Wirtschaftspolitik. Vize-Präsidentin SVP Schweiz.","title":"Politik"},{"title":"Partei","imageSrc":"https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=600&q=80","description":"Mitglied des Parteileitungsausschusses SVP Schweiz. Mitglied Parteileitung SVP Schweiz."}]}
      />
            </div>
  );
}
