// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroStickerFlip from "@/components/sections/hero/HeroStickerFlip";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
              <HeroStickerFlip
        title="Magdalena Martullo-Blocher"
        description="Entrepreneur & National Councilor"
        imageSrc="https://picsum.photos/seed/1365764607/1200/800"
        backTextSegments={[{"type":"text","content":"I am a passionate "},{"content":"entrepreneur","type":"highlight"},{"type":"text","content":" and dedicated "},{"type":"highlight","content":"politician"},{"type":"text","content":", committed to a strong "},{"type":"highlight","content":"Swiss economy"},{"type":"text","content":" and independence."}]}
        clickBadgeText="About Me"
        stickerImageSrcs={["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&q=80","https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&q=80","https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1783293465780-ovbejkk6.jpg","https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=400&q=80","https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1783293465780-kcr9uclo.jpg","https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1783293465775-xgm025py.jpg","https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1783293465780-ovbejkk6.jpg","https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1783293527459-3068k3c8.jpg"]}
        socialLinks={[{"label":"Twitter","iconSrc":"https://storage.googleapis.com/webild/default/templates/anya/icons/twitter.svg","href":"#"},{"href":"https://www.martullo-blocher.ch/","iconSrc":"https://storage.googleapis.com/webild/default/templates/anya/icons/instagram.svg","label":"Website"}]}
      />
            </div>
  );
}
