// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroStickerFlip from "@/components/sections/hero/HeroStickerFlip";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
              <HeroStickerFlip
                title="Hey, I'm Anya"
                description="Blogger & Traveler"
                imageSrc="https://storage.googleapis.com/webild/default/templates/anya/hero.webp"
                backTextSegments={[
                  { type: "text", content: "I'm currently " },
                  { type: "photo", src: "https://storage.googleapis.com/webild/default/templates/anya/inline-photo.webp" },
                  { type: "highlight", content: " traveling all over the world " },
                  { type: "text", content: "capturing moments, " },
                  { type: "highlight", content: "writing stories " },
                  { type: "text", content: "and sharing the " },
                  { type: "highlight", content: "places I love" },
                ]}
                clickBadgeText="Click me!"
                stickerImageSrcs={[
                  "https://storage.googleapis.com/webild/default/templates/anya/stickers/mixtape.webp",
                  "https://storage.googleapis.com/webild/default/templates/anya/stickers/flowers.webp",
                  "https://storage.googleapis.com/webild/default/templates/anya/stickers/toast.webp",
                  "https://storage.googleapis.com/webild/default/templates/anya/stickers/passport.webp",
                  "https://storage.googleapis.com/webild/default/templates/anya/stickers/cd.webp",
                  "https://storage.googleapis.com/webild/default/templates/anya/stickers/reading.webp",
                  "https://storage.googleapis.com/webild/default/templates/anya/stickers/watercolors.webp",
                  "https://storage.googleapis.com/webild/default/templates/anya/stickers/orange.webp",
                ]}
                socialLinks={[
                  { iconSrc: "https://storage.googleapis.com/webild/default/templates/anya/icons/instagram.svg", href: "#", label: "Instagram" },
                  { iconSrc: "https://storage.googleapis.com/webild/default/templates/anya/icons/tiktok.svg", href: "#", label: "TikTok" },
                  { iconSrc: "https://storage.googleapis.com/webild/default/templates/anya/icons/twitter.svg", href: "#", label: "Twitter" },
                ]}
              />
            </div>
  );
}
