// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "milestones" section.

import React from 'react';
import FeaturesCarouselMarquee from "@/components/sections/features/FeaturesCarouselMarquee";

export default function MilestonesSection(): React.JSX.Element {
  return (
    <div id="milestones" data-section="milestones">
              <FeaturesCarouselMarquee
                textAnimation="fade"
                tag="Life in Frames"
                title="Moments I'll Never Forget"
                description="Big milestones, quiet sunsets, and everything worth remembering in between."
                primaryButton={{ text: "See the full gallery", href: "#gallery" }}
                secondaryButton={{ text: "Follow my journey", href: "#follow" }}
                items={[
                  { imageSrc: "https://storage.googleapis.com/webild/default/templates/anya/carousel/graduation.webp", label: "Graduation Day" },
                  { imageSrc: "https://images.unsplash.com/photo-1527668752968-14dc70a27c95?w=600&q=80", label: "Swiss Alps" },
                  { imageSrc: "https://storage.googleapis.com/webild/default/templates/anya/carousel/solo-trip.webp", label: "First Solo Trip" },
                  { imageSrc: "https://storage.googleapis.com/webild/default/templates/anya/carousel/golden-hour.webp", label: "Golden Hour" },
                  { imageSrc: "https://storage.googleapis.com/webild/default/templates/anya/carousel/turning-25.webp", label: "Turning 25" },
                  { imageSrc: "https://storage.googleapis.com/webild/default/templates/anya/carousel/island-life.webp", label: "Island Life" },
                ]}
              />
            </div>
  );
}
