// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "milestones" section.

import React from 'react';
import FeaturesCarouselMarquee from "@/components/sections/features/FeaturesCarouselMarquee";

export default function MilestonesSection(): React.JSX.Element {
  return (
    <div id="milestones" data-section="milestones">
              <FeaturesCarouselMarquee
        textAnimation="fade"
        tag="Milestones"
        title="A Journey of Commitment"
        description="Key moments in my entrepreneurial and political career."
        items={[{"label":"EMS-CHEMIE Leadership","imageSrc":"https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1783295499792-01tf7qtl.jpg"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1783294806136-amcdbrxz.jpg","label":"National Council Election"},{"label":"Advocating for Economy","imageSrc":"https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1783293850228-lmohsh6b.jpg"},{"label":"Swiss Independence","imageSrc":"https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1783295369512-i1rpbyoy.jpg"},{"label":"Innovation Focus","imageSrc":"https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1783295499793-bvdbvvam.png"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1783295499795-fvvig7oh.jpg","label":"Global Expansion"}]}
      />
            </div>
  );
}
