/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { useRef } from "react";
import { motion, useScroll, useTransform } from "motion/react";
import ImageOrVideo from "@/components/ui/ImageOrVideo";

type FeaturesParallaxShowcaseProps = {
  title: string;
  leftImageSrc: string;
  rightImageSrc: string;
} & ({ backgroundSrc: string; backgroundVideoSrc?: never } | { backgroundVideoSrc: string; backgroundSrc?: never });

const ShowcaseInline = () => {
  const sectionRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: sectionRef,
    offset: ["start end", "end start"],
  });

  const leftY = useTransform(scrollYProgress, [0, 1], ["-10%", "20%"]);
  const leftRotate = useTransform(scrollYProgress, [0, 1], [-13, 8]);
  const rightY = useTransform(scrollYProgress, [0, 1], ["-5%", "25%"]);
  const rightRotate = useTransform(scrollYProgress, [0, 1], [6, -7]);

  return (
    <section
      ref={sectionRef}
      aria-label="Parallax showcase section"
      className="relative w-full h-svh overflow-hidden my-20"
    >
      <div className="absolute inset-0">
        <ImageOrVideo imageSrc={"https://images.unsplash.com/photo-1527668752968-14dc70a27c95?w=1200&q=80"} className="w-full h-full object-cover" />
      </div>

      <div className="relative z-10 w-full pt-32 md:pt-48 text-center">
        <h2 className="text-7xl md:text-8xl text-white font-serif">
          {"For a Strong Switzerland \n                  🇨🇭"}
        </h2>
      </div>

      <motion.div
        style={{ y: leftY, rotate: leftRotate }}
        className="absolute left-[5%] md:left-[12%] top-[28%] md:top-[2%] w-[50vw] md:w-[26vw] max-w-[420px] drop-shadow-2xl pointer-events-none"
      >
        <ImageOrVideo imageSrc={"https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1783294133902-jfwtklo3.jpg"} className="w-full h-auto" />
      </motion.div>

      <motion.div
        style={{ y: rightY, rotate: rightRotate }}
        className="absolute right-[5%] md:right-[12%] top-[60%] md:top-[12%] w-[45vw] md:w-[20vw] max-w-[340px] drop-shadow-2xl pointer-events-none"
      >
        <div className="relative">
          <ImageOrVideo imageSrc={"https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=400&q=80"} className="w-full h-auto rounded-2xl" />
          <div className="absolute top-3 right-3 text-4xl drop-shadow-md">🇨🇭</div>
        </div>
      </motion.div>
    </section>
  );
};

export default function ShowcaseSection() {
  return (
    <div data-webild-section="showcase" data-section="showcase" id="showcase">
      <ShowcaseInline />
    </div>
  );
}
